# Copy the configuration below and add it to your
# ~/.config/alacritty/alacritty.toml file

[font]
normal = { family = "0xProto Nerd Font Mono" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 13

[cursor]
style = { shape = "Block", blinking = "Off" }

[terminal.shell]
program = "tmux"

[general]
import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]
