## Keybinds

set -g mode-keys vi
set -g base-index 1
set -g renumber-windows on
set -g mouse on
set -g status-interval 1

# Panes splitting
bind \\ split-window -h -c '#{pane_current_path}'
bind - split-window -v -c '#{pane_current_path}'
unbind '"'
unbind %

# Windows
bind -n M-n new-window -c '#{pane_current_path}'
bind -n M-, previous-window
bind -n M-. next-window
bind -n M-< command-prompt -I'#W' { rename-window -- '%%' }
bind -n M-Left swap-window -t -1\; select-window -t -1
bind -n M-Right swap-window -t +1\; select-window -t +1
bind -n M-1 select-window -t:1
bind -n M-2 select-window -t:2
bind -n M-3 select-window -t:3
bind -n M-4 select-window -t:4
bind -n M-5 select-window -t:5
bind -n M-6 select-window -t:6
bind -n M-7 select-window -t:7
bind -n M-8 select-window -t:8
bind -n M-9 select-window -t:9

bind -n M-H if -F "#{pane_at_left}" "" "select-pane -L"
bind -n M-L if -F "#{pane_at_right}" "" "select-pane -R"
bind -n M-K if -F "#{pane_at_top}" "" "select-pane -U"
bind -n M-J if -F "#{pane_at_bottom}" "" "select-pane -D"
bind -n M-q kill-pane

bind r source-file $HOME/.config/tmux/tmux.conf

# Kill window with q
unbind q
bind q kill-window

# Disable bell
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# Copy mode keybinds
unbind [
bind -n M-c copy-mode
set -s copy-command 'xclip -i'
bind -Tcopy-mode-vi MouseDragEnd1Pane send -X copy-pipe-no-clear
bind -Tcopy-mode-vi Space send -X rectangle-toggle
bind -Tcopy-mode-vi v send -X begin-selection
bind -Tcopy-mode-vi y send -X copy-pipe
bind -Tcopy-mode-vi u send -X copy-pipe-line
bind -Tcopy-mode-vi C-k send-keys -X halfpage-up
bind -Tcopy-mode-vi C-j send-keys -X halfpage-down

set -g @catppuccin_flavor 'mocha'

set -g @catppuccin_window_status_style 'rounded'
set -g @catppuccin_window_fill "number"
set -g @catppuccin_window_text " #{?automatic-rename,#{pane_current_path},#W}"

set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text " #{?automatic-rename,#{pane_current_path},#W}"

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
set -g status-right-length 100

set -g status-right "#{E:@catppuccin_status_application}#{E:@catppuccin_status_session}"
set -g status-left ""

set -g default-command /usr/bin/fish
set -g default-shell /usr/bin/fish
