## Keybinds
# Change prefix
unbind C-b
set-option -g prefix `
bind-key ` send-prefix

# Panes splitting
bind \\ split-window -h -c '#{pane_current_path}'
bind - split-window -v -c '#{pane_current_path}'
unbind '"'
unbind %

# Windows
bind c new-window -c '#{pane_current_path}'

# Start numbering windows from index 1
set -g base-index 1

# Config reload
bind r source-file ~/.config/tmux/tmux.conf

# Kill window with q
unbind q
bind q kill-window


# Switch panes using Meta + vim keys without prefix
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D
bind -n M-q kill-pane

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# Disable bell
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# Copy mode keybinds

set -s copy-command 'xclip -i'
bind -Tcopy-mode-vi MouseDragEnd1Pane send -X copy-pipe-no-clear
bind -Tcopy-mode-vi Space send -X rectangle-toggle
bind -Tcopy-mode-vi v send -X begin-selection
bind -Tcopy-mode-vi y send -X copy-pipe-and-cancel
bind -Tcopy-mode-vi u send -X copy-pipe-line-and-cancel

## Styles
# clock mode
setw -g clock-mode-colour brightyellow

# copy mode
setw -g mode-style 'fg=black bg=green bold'

# panes
set -g pane-border-style 'fg=black'
set -g pane-active-border-style 'fg=green'

# statusbar
set -g status-position bottom
set -g status-justify left
set -g status-style 'bg=green'

set -g status-left ''
set -g status-right ''

setw -g window-status-current-style 'fg=black bg=#ffd369'
setw -g window-status-current-format ' #I #W #F '

setw -g window-status-style 'fg=black'
setw -g window-status-format ' #I #W #F '
